import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const FinProductHubApp());
}

class FinProductHubApp extends StatelessWidget {
  const FinProductHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FinanceHub India',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1E3A8A),
          primary: const Color(0xFF1E3A8A),
          secondary: const Color(0xFF0D9488),
          surface: const Color(0xFFF8FAFC),
        ),
        fontFamily: 'Roboto',
      ),
      home: const SplashScreen(),
    );
  }
}

enum ProductCategory { creditCard, personalLoan }

class FinancialProduct {
  final String id;
  final String name;
  final String issuer;
  final String logoUrl;
  final ProductCategory category;
  final String headline;
  final List<String> keyBenefits;
  final String feeOrInterest;
  final String eligibility;
  final List<String> requiredDocs;
  final String applyUrl;
  final String? badgeText;

  FinancialProduct({
    required this.id,
    required this.name,
    required this.issuer,
    required this.logoUrl,
    required this.category,
    required this.headline,
    required this.keyBenefits,
    required this.feeOrInterest,
    required this.eligibility,
    required this.requiredDocs,
    required this.applyUrl,
    this.badgeText,
  });
}

final List<FinancialProduct> financialProductsCatalog = [
  // ==================== 10 CREDIT CARDS ====================
  FinancialProduct(
    id: 'cc_1',
    name: 'Axis Bank MyZone Credit Card',
    issuer: 'Axis Bank',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.creditCard,
    headline: 'Ideal for entertainment, dining & UPI payments',
    keyBenefits: [
      'Flat ₹120 off on Swiggy on min orders of ₹500',
      'Buy 1 Get 1 Free on movie tickets via District/Paytm Movies',
      'Complimentary domestic airport lounge access',
      'RuPay variant available for direct UPI payments',
    ],
    feeOrInterest: 'Annual Fee: ₹500 + GST (Waived on ₹1.5L spends)',
    eligibility: 'Salaried / Self-Employed | Age: 21-65 yrs | Min Income: ₹25,000/mo',
    requiredDocs: ['PAN Card', 'Address Proof', 'Latest 3 Months Salary Slips/ITR'],
    applyUrl: 'https://bitli.in/jv53q08',
    badgeText: 'Popular UPI Card',
  ),
  FinancialProduct(
    id: 'cc_2',
    name: 'SBI Cashback Credit Card',
    issuer: 'SBI Card',
    logoUrl: 'https://companieslogo.com/img/orig/SBIN.NS-7e289c49.png',
    category: ProductCategory.creditCard,
    headline: 'Flat 5% cashback on online spends',
    keyBenefits: [
      '5% Cashback on online merchant purchases',
      '1% Cashback on offline spends',
      'Auto-credit cashback into statement balance',
      '1% Fuel surcharge waiver',
    ],
    feeOrInterest: 'Joining & Annual Fee: ₹999 + GST (Waived on ₹2L spends)',
    eligibility: 'Age: 21-65 yrs | CIBIL: 720+ | Min Income: ₹30,000/mo',
    requiredDocs: ['PAN Card', 'Address Proof', 'Latest 3 Months Bank Statements'],
    applyUrl: 'https://bitli.in/y04ENvz',
    badgeText: '5% Cashback',
  ),
  FinancialProduct(
    id: 'cc_3',
    name: 'Axis Bank Indian Oil Credit Card',
    issuer: 'Axis Bank',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.creditCard,
    headline: 'Save up to 4% value back on fuel at IndianOil',
    keyBenefits: [
      '4% value back as reward points at Indian Oil outlets',
      '1% Fuel surcharge waiver on transactions ₹200-₹5000',
      '1% value back on online shopping',
      'Discount on BookMyShow movie tickets',
    ],
    feeOrInterest: 'Joining Fee: ₹500 (Waived on ₹50,000 annual spend)',
    eligibility: 'Salaried & Self-Employed | Age: 21-65 yrs | CIBIL: 700+',
    requiredDocs: ['PAN Card', 'Identity Proof', 'Income Proof'],
    applyUrl: 'https://bitli.in/jv53q08',
    badgeText: 'Fuel Saver',
  ),
  FinancialProduct(
    id: 'cc_4',
    name: 'RBL Bank Shoprite Credit Card',
    issuer: 'RBL Bank',
    logoUrl: 'https://companieslogo.com/img/orig/RBLBANK.NS-99b828a5.png',
    category: ProductCategory.creditCard,
    headline: 'Zero annual fee card for grocery shopping & movie rewards',
    keyBenefits: [
      'Lifetime Free offer for eligible applicants',
      '20 Reward Points per ₹100 spent on Groceries',
      '10% discount on BookMyShow tickets',
      '1 Reward Point per ₹100 on other spends',
    ],
    feeOrInterest: 'Joining & Annual Fee: Lifetime Free / Nil',
    eligibility: 'Age: 21-65 yrs | CIBIL: 680+ | Salaried / Self-Employed',
    requiredDocs: ['PAN Card', 'Address Proof', 'Recent Photo'],
    applyUrl: 'https://bitli.in/gnn9nk5',
    badgeText: 'Lifetime Free',
  ),
  FinancialProduct(
    id: 'cc_5',
    name: 'Kiwi UPI RuPay Credit Card',
    issuer: 'Kiwi / Axis Bank',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.creditCard,
    headline: 'Scan & Pay via UPI with virtual credit card',
    keyBenefits: [
      'Scan any merchant QR code & pay directly via UPI',
      'Up to 2% flat cashback on UPI transactions',
      '100% digital instant approval and virtual issuance',
      'Zero joining fee & zero annual fee',
    ],
    feeOrInterest: 'Lifetime Free (Zero Annual Charges)',
    eligibility: 'Age: 21-55 yrs | Valid PAN & mobile | CIBIL: 650+',
    requiredDocs: ['PAN Card', 'Paperless Instant Digital e-KYC'],
    applyUrl: 'https://bitli.in/whEK3co',
    badgeText: 'Instant UPI Card',
  ),
  FinancialProduct(
    id: 'cc_6',
    name: 'HDFC Bank IRCTC Credit Card',
    issuer: 'HDFC Bank',
    logoUrl: 'https://companieslogo.com/img/orig/HDB-642cf326.png',
    category: ProductCategory.creditCard,
    headline: 'Train ticket savings & railway lounge visits',
    keyBenefits: [
      'Up to 5% cashback on train tickets via IRCTC app',
      'Complimentary access to select Executive Railway Lounges',
      '1% transaction charge waiver on IRCTC',
      '₹500 IRCTC welcome voucher on activation',
    ],
    feeOrInterest: 'Annual Fee: ₹500 + GST (Waived on ₹1.5L spends)',
    eligibility: 'Age: 21-60 yrs | Min Income: ₹25,000/mo | CIBIL: 700+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Salary Slips'],
    applyUrl: 'https://bitli.in/oekzuQt',
    badgeText: 'Train Travel',
  ),
  FinancialProduct(
    id: 'cc_7',
    name: 'SBI SimplyCLICK Credit Card',
    issuer: 'SBI Card',
    logoUrl: 'https://companieslogo.com/img/orig/SBIN.NS-7e289c49.png',
    category: ProductCategory.creditCard,
    headline: '10X reward multipliers on major online platforms',
    keyBenefits: [
      '10X Reward Points on Amazon, BookMyShow, Cleartrip & Swiggy',
      '5X Reward Points on all other online spends',
      '₹500 Amazon Gift Card as welcome benefit',
      'Milestone travel e-vouchers up to ₹4,000 yearly',
    ],
    feeOrInterest: 'Joining & Annual: ₹499 + GST (Waived on ₹1L spends)',
    eligibility: 'Salaried: ₹25k/mo | Self-Employed: ₹4.8L ITR | CIBIL: 720+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Latest Salary Slip / ITR'],
    applyUrl: 'https://bitli.in/y04ENvz',
    badgeText: 'Online Spends',
  ),
  FinancialProduct(
    id: 'cc_8',
    name: 'SBI SimplySAVE Credit Card',
    issuer: 'SBI Card',
    logoUrl: 'https://companieslogo.com/img/orig/SBIN.NS-7e289c49.png',
    category: ProductCategory.creditCard,
    headline: 'High rewards on daily essentials, groceries & dining',
    keyBenefits: [
      '10 Reward Points per ₹150 on Dining, Movies & Groceries',
      'Welcome bonus 2,000 reward points (worth ₹500)',
      '1% Fuel Surcharge Waiver',
      'Emergency card replacement facility worldwide',
    ],
    feeOrInterest: 'Joining & Annual: ₹499 + GST (Waived on ₹1L spends)',
    eligibility: 'Age: 21-65 yrs | Min Income: ₹30,000/mo',
    requiredDocs: ['PAN Card', 'Address Proof', 'Income Proof'],
    applyUrl: 'https://bitli.in/f3fwpwO',
    badgeText: 'Daily Essentials',
  ),
  FinancialProduct(
    id: 'cc_9',
    name: 'BOBCARD Eterna Credit Card',
    issuer: 'Bank of Baroda',
    logoUrl: 'https://companieslogo.com/img/orig/BANKBARODA.BO-d2bbdae3.png',
    category: ProductCategory.creditCard,
    headline: 'Premium card with unlimited domestic lounge access',
    keyBenefits: [
      'First Year Free welcome program',
      'Unlimited complimentary domestic airport lounge access',
      '15 Reward Points per ₹100 on dining & travel',
      'Buy 1 Get 1 free movie tickets every month via District app',
    ],
    feeOrInterest: 'First Year Free (Renewal: ₹2,499; Waived on ₹2.5L spends)',
    eligibility: 'Age: 21-65 yrs | Annual Income: ₹12L/yr | CIBIL: 650+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Salary Slips / ITR'],
    applyUrl: 'https://bitli.in/2icw2gT',
    badgeText: 'Lounge Access',
  ),
  FinancialProduct(
    id: 'cc_10',
    name: 'BOBCARD Classic / Platinum',
    issuer: 'Bank of Baroda',
    logoUrl: 'https://companieslogo.com/img/orig/BANKBARODA.BO-d2bbdae3.png',
    category: ProductCategory.creditCard,
    headline: 'Dependable card with merchant savings & easy EMI',
    keyBenefits: [
      'Reward points redeemable for shopping & travel',
      '1% fuel surcharge waiver',
      'Easy 1-click EMI conversion options',
      'Complimentary accidental insurance coverage',
    ],
    feeOrInterest: 'Nominal joining fee with milestone waivers',
    eligibility: 'Age: 21-65 yrs | Salaried & Self-Employed | CIBIL: 650+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Bank Statements'],
    applyUrl: 'https://bitli.in/gnn9nk5',
    badgeText: 'Everyday Value',
  ),

  // ==================== 13 PERSONAL LOANS ====================
  FinancialProduct(
    id: 'loan_1',
    name: 'Axis Bank Personal Loan',
    issuer: 'Axis Bank',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.personalLoan,
    headline: 'High ticket personal loans up to ₹40 Lakhs',
    keyBenefits: [
      'Borrow from ₹50,000 up to ₹40 Lakhs',
      'Interest rates starting from 9.99% p.a.',
      'Flexible tenure up to 84 months',
      'Balance transfer facility available',
    ],
    feeOrInterest: 'Interest: From 9.99% p.a. | Tenure: Up to 84 mos',
    eligibility: 'Salaried | Age: 21-60 yrs | Income: ₹30k/mo | CIBIL: 700+',
    requiredDocs: ['PAN Card', 'Address Proof', '3 Mos Salary Slips'],
    applyUrl: 'https://bitli.in/jv53q08',
    badgeText: 'Up to ₹40 Lakhs',
  ),
  FinancialProduct(
    id: 'loan_2',
    name: 'Poonawalla Fincorp Personal Loan',
    issuer: 'Poonawalla Fincorp',
    logoUrl: 'https://companieslogo.com/img/orig/POONAWALLA.NS-1811805b.png',
    category: ProductCategory.personalLoan,
    headline: '100% digital journey with zero foreclosure charges',
    keyBenefits: [
      'Instant digital approval up to ₹15 Lakhs',
      'Zero prepayment and zero foreclosure charges',
      'Interest starting from 11.50% p.a.',
      'Paperless online processing',
    ],
    feeOrInterest: 'Interest: From 11.50% p.a. | Tenure: Up to 84 mos',
    eligibility: 'Age: 24-55 yrs | Min Income: ₹3L/yr | CIBIL: 720+',
    requiredDocs: ['PAN Card', 'Address Proof'],
    applyUrl: 'https://bitli.in/ADi9XMg',
    badgeText: 'Zero Foreclosure',
  ),
  FinancialProduct(
    id: 'loan_3',
    name: 'Bajaj Finserv Personal Loan',
    issuer: 'Bajaj Finserv',
    logoUrl: 'https://companieslogo.com/img/orig/BAJAJFINSV.NS-826a7e58.png',
    category: ProductCategory.personalLoan,
    headline: 'High funding up to ₹55 Lakhs with Flexi facility',
    keyBenefits: [
      'Sanctioned loan amount up to ₹55 Lakhs',
      'Flexi facility: Pay interest solely on amount used',
      'Flexible tenure up to 96 months',
      'Fast direct bank account disbursement',
    ],
    feeOrInterest: 'Interest: From 11.00% p.a. | Tenure: Up to 96 mos',
    eligibility: 'Salaried | Age: 25-57 yrs | Min Income: ₹35k/mo | CIBIL: 685+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Bank Statements'],
    applyUrl: 'https://bitli.in/hsuwdq4',
    badgeText: 'Flexi Overdraft',
  ),
  FinancialProduct(
    id: 'loan_4',
    name: 'Tata Capital Personal Loan',
    issuer: 'Tata Capital',
    logoUrl: 'https://companieslogo.com/img/orig/TATACONSUM.NS-5527ca3d.png',
    category: ProductCategory.personalLoan,
    headline: 'Instant loan backed by Tata Trust',
    keyBenefits: [
      'Personal loan and overdraft up to ₹35 Lakhs',
      'Interest rates starting from 10.99% p.a.',
      'Flexible tenure up to 84 months',
      'Seamless balance transfer facility',
    ],
    feeOrInterest: 'Interest: From 10.99% p.a. | Tenure: Up to 84 mos',
    eligibility: 'Salaried | Age: 21-58 yrs | Min Income: ₹25k/mo | CIBIL: 725+',
    requiredDocs: ['PAN Card', 'Address Proof', '3 Mos Bank Statements'],
    applyUrl: 'https://bitli.in/XU9d9v1',
    badgeText: 'Low ROI 10.99%',
  ),
  FinancialProduct(
    id: 'loan_5',
    name: 'HDFC Bank Personal Loan',
    issuer: 'HDFC Bank',
    logoUrl: 'https://companieslogo.com/img/orig/HDB-642cf326.png',
    category: ProductCategory.personalLoan,
    headline: 'Maximum loan disbursal up to ₹75 Lakhs',
    keyBenefits: [
      'Disbursal capacity up to ₹75 Lakhs',
      'Interest starting from 9.99% p.a.',
      'Instant disbursal for pre-approved holders',
      'Tenure up to 84 months',
    ],
    feeOrInterest: 'Interest: From 9.99% p.a. | Tenure: Up to 84 mos',
    eligibility: 'Salaried | Age: 21-60 yrs | Income: ₹30k/mo | CIBIL: 700+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Salary Slips'],
    applyUrl: 'https://bitli.in/oekzuQt',
    badgeText: 'Up to ₹75 Lakhs',
  ),
  FinancialProduct(
    id: 'loan_6',
    name: 'Olyv Instant Personal Loan',
    issuer: 'Olyv',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.personalLoan,
    headline: 'Quick digital credit up to ₹2 Lakhs',
    keyBenefits: [
      'Instant loans up to ₹2,00,000',
      '100% Mobile paperless journey',
      'Open to Salaried and Self-Employed',
      'Quick direct bank transfer',
    ],
    feeOrInterest: 'Competitive rates | Flexible short tenure',
    eligibility: 'Age: 21-45 yrs | Min Income: ₹20k/mo | CIBIL: 680+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Bank Statements'],
    applyUrl: 'https://bitli.in/oToYr46',
    badgeText: 'Instant ₹2 Lakhs',
  ),
  FinancialProduct(
    id: 'loan_7',
    name: 'Prefr Instant Personal Loan',
    issuer: 'Prefr Loans',
    logoUrl: 'https://companieslogo.com/img/orig/BAJAJFINSV.NS-826a7e58.png',
    category: ProductCategory.personalLoan,
    headline: '24x7 digital lending access with Account Aggregator',
    keyBenefits: [
      'Digital loan up to ₹3,00,000',
      'Fast automated approval via RBI Account Aggregator',
      'Open for salaried and self-employed',
      'Flexible repayment options',
    ],
    feeOrInterest: 'Transparent digital processing',
    eligibility: 'Age: 22-55 yrs | Min Income: ₹25k/mo | CIBIL: 725+',
    requiredDocs: ['PAN Card', 'Digital Account Aggregator / Pay Slips'],
    applyUrl: 'https://bitli.in/98YszFL',
    badgeText: '24x7 Access',
  ),
  FinancialProduct(
    id: 'loan_8',
    name: 'Zype Instant Personal Loan',
    issuer: 'Zype Lending',
    logoUrl: 'https://companieslogo.com/img/orig/RBLBANK.NS-99b828a5.png',
    category: ProductCategory.personalLoan,
    headline: 'Instant 60-second credit line up to ₹1.5 Lakhs',
    keyBenefits: [
      'Line of credit up to ₹1,50,000 in 60 seconds',
      'Zero physical paperwork required',
      'Zero foreclosure fees on early payback',
      'Repayment from 6 to 12 months',
    ],
    feeOrInterest: 'Zero Foreclosure Fee',
    eligibility: 'Salaried Only | Age: 21-50 yrs | Income: ₹20k/mo | CIBIL: 650+',
    requiredDocs: ['Paperless - Instant mobile verification'],
    applyUrl: 'https://bitli.in/cXtTNIP',
    badgeText: '60-Sec Approval',
  ),
  FinancialProduct(
    id: 'loan_9',
    name: 'MyEazyLoan Marketplace',
    issuer: 'MyEazyLoan Partners',
    logoUrl: 'https://companieslogo.com/img/orig/HDB-642cf326.png',
    category: ProductCategory.personalLoan,
    headline: 'Compare quotes from 6+ top banks in single check',
    keyBenefits: [
      'Compare HDFC, Axis, Bajaj, Tata Capital in one place',
      'Side-by-side comparison of interest rates & EMIs',
      'Avoid multiple hard CIBIL inquiries',
      'High approval rates',
    ],
    feeOrInterest: 'Starts from 9.99% p.a.',
    eligibility: 'Age: 18-60 yrs | Salaried & Self-Employed | CIBIL: 700+',
    requiredDocs: ['PAN Card', 'Address Proof', 'Bank Statements'],
    applyUrl: 'https://bitli.in/whEK3co',
    badgeText: 'Compare & Save',
  ),
  FinancialProduct(
    id: 'loan_10',
    name: 'Fibe Instant Personal Loan',
    issuer: 'Fibe',
    logoUrl: 'https://companieslogo.com/img/orig/SBIN.NS-7e289c49.png',
    category: ProductCategory.personalLoan,
    headline: 'Zero foreclosure charges with instant account crediting',
    keyBenefits: [
      'Personal loan up to ₹5,00,000',
      'Zero foreclosure fees - pay anytime',
      'Pay interest only on amount used',
      'Instant direct bank transfer',
    ],
    feeOrInterest: 'Interest from 20% p.a. | Up to 36 mos',
    eligibility: 'Salaried Only | Age: 19-55 yrs | Income: ₹20k/mo | CIBIL: 680+',
    requiredDocs: ['PAN Card', 'Bank Statements'],
    applyUrl: 'https://bitli.in/fle3BLs',
    badgeText: 'Zero Foreclosure',
  ),
  FinancialProduct(
    id: 'loan_11',
    name: 'Ram Fincorp Personal Loan',
    issuer: 'Ram Fincorp',
    logoUrl: 'https://companieslogo.com/img/orig/BANKBARODA.BO-d2bbdae3.png',
    category: ProductCategory.personalLoan,
    headline: 'Instant loan from ₹1,000 to ₹2 Lakhs with DigiLocker',
    keyBenefits: [
      'Micro-loans from ₹1,000 up to ₹2,00,000',
      'Fast 5-minute approval with instant disbursal',
      'No lock-in and zero foreclosure charges',
      '100% paperless via DigiLocker e-KYC',
    ],
    feeOrInterest: 'Zero prepayment penalty',
    eligibility: 'Salaried | Age: 18-58 yrs | Income: ₹18k/mo | CIBIL: 600+',
    requiredDocs: ['PAN Card', 'Address Proof (DigiLocker)', 'Bank Statements'],
    applyUrl: 'https://bitli.in/4g71y3b',
    badgeText: 'DigiLocker KYC',
  ),
  FinancialProduct(
    id: 'loan_12',
    name: 'ZapCash Instant Personal Loan',
    issuer: 'ZapCash',
    logoUrl: 'https://companieslogo.com/img/orig/POONAWALLA.NS-1811805b.png',
    category: ProductCategory.personalLoan,
    headline: 'Unsecured loan with low credit score or new-to-credit',
    keyBenefits: [
      'Accessible with CIBIL as low as 500 or no history',
      'Unsecured loan up to ₹50,000',
      'No collateral or guarantor required',
      'Quick app-based processing',
    ],
    feeOrInterest: 'Personalized interest rates',
    eligibility: 'Salaried & Self-Employed | Age: 21-60 yrs | CIBIL: 500+',
    requiredDocs: ['PAN Card', 'Bank Statements', 'Business Proof'],
    applyUrl: 'https://bitli.in/j4wOikD',
    badgeText: 'Low CIBIL (500+)',
  ),
  FinancialProduct(
    id: 'loan_13',
    name: 'CreditSea Personal Loan',
    issuer: 'CreditSea',
    logoUrl: 'https://companieslogo.com/img/orig/AXISBANK.BO-8f615301.png',
    category: ProductCategory.personalLoan,
    headline: 'Instant loan up to ₹2 Lakhs with zero prepayment charges',
    keyBenefits: [
      'Digital loan from ₹5,000 up to ₹2,00,000',
      'Approval in 5 minutes with low credit score (500+)',
      'Zero prepayment and zero foreclosure penalties',
      'Tenures from 3 to 36 months',
    ],
    feeOrInterest: 'Interest: 14% to 36% p.a. | Tenure: 3-36 mos',
    eligibility: 'Age: 22-50 yrs | Salaried (₹25k) & Self-Employed (₹50k) | CIBIL: 500+',
    requiredDocs: ['PAN Card', 'Address Proof (DigiLocker)', 'Bank Statements'],
